# Generated by Django 5.1 on 2024-08-18 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255)),
                ('difficulty', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
